Resources:
  urlsTableD98564E7:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: shortUrl
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: shortUrl
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      TableName: urls-Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: UrlShortenerSvcStack/urls-Table/Resource
  ShortenerFunctionServiceRoleADA653A5:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: UrlShortenerSvcStack/ShortenerFunction/ServiceRole/Resource
  ShortenerFunctionServiceRoleDefaultPolicyB26EB9E1:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
              - dynamodb:ConditionCheckItem
              - dynamodb:DeleteItem
              - dynamodb:DescribeTable
              - dynamodb:GetItem
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:PutItem
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:UpdateItem
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - urlsTableD98564E7
                  - Arn
              - Ref: AWS::NoValue
        Version: "2012-10-17"
      PolicyName: ShortenerFunctionServiceRoleDefaultPolicyB26EB9E1
      Roles:
        - Ref: ShortenerFunctionServiceRoleADA653A5
    Metadata:
      aws:cdk:path: UrlShortenerSvcStack/ShortenerFunction/ServiceRole/DefaultPolicy/Resource
  ShortenerFunction2C447D23:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: f8a29218343b9813e77e3515651d30a0de7003c6ef94c451bd7b5d94536ceb2b.zip
      Role:
        Fn::GetAtt:
          - ShortenerFunctionServiceRoleADA653A5
          - Arn
      Environment:
        Variables:
          TABLE_NAME:
            Ref: urlsTableD98564E7
      Handler: index.handler
      Runtime: nodejs16.x
    DependsOn:
      - ShortenerFunctionServiceRoleDefaultPolicyB26EB9E1
      - ShortenerFunctionServiceRoleADA653A5
    Metadata:
      aws:cdk:path: UrlShortenerSvcStack/ShortenerFunction/Resource
      aws:asset:path: asset.f8a29218343b9813e77e3515651d30a0de7003c6ef94c451bd7b5d94536ceb2b
      aws:asset:is-bundled: false
      aws:asset:property: Code
  ShortenerApi3A8B5181:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: ShortenerApi
    Metadata:
      aws:cdk:path: UrlShortenerSvcStack/ShortenerApi/Resource
  ShortenerApiDeployment11C72100d9ffac98da373362b25e620ba0ac908e:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: ShortenerApi3A8B5181
      Description: Automatically created by the RestApi construct
    DependsOn:
      - ShortenerApishortenPOST6FA1D6B0
      - ShortenerApishortenDE5AC227
    Metadata:
      aws:cdk:path: UrlShortenerSvcStack/ShortenerApi/Deployment/Resource
  ShortenerApiDeploymentStageprodD11A25C3:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: ShortenerApi3A8B5181
      DeploymentId:
        Ref: ShortenerApiDeployment11C72100d9ffac98da373362b25e620ba0ac908e
      StageName: prod
    Metadata:
      aws:cdk:path: UrlShortenerSvcStack/ShortenerApi/DeploymentStage.prod/Resource
  ShortenerApishortenDE5AC227:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - ShortenerApi3A8B5181
          - RootResourceId
      PathPart: shorten
      RestApiId:
        Ref: ShortenerApi3A8B5181
    Metadata:
      aws:cdk:path: UrlShortenerSvcStack/ShortenerApi/Default/shorten/Resource
  ShortenerApishortenPOSTApiPermissionUrlShortenerSvcStackShortenerApi3DEC1041POSTshortenA0ABA880:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - ShortenerFunction2C447D23
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: ShortenerApi3A8B5181
            - /
            - Ref: ShortenerApiDeploymentStageprodD11A25C3
            - /POST/shorten
    Metadata:
      aws:cdk:path: UrlShortenerSvcStack/ShortenerApi/Default/shorten/POST/ApiPermission.UrlShortenerSvcStackShortenerApi3DEC1041.POST..shorten
  ShortenerApishortenPOSTApiPermissionTestUrlShortenerSvcStackShortenerApi3DEC1041POSTshorten900B0BCC:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - ShortenerFunction2C447D23
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: ShortenerApi3A8B5181
            - /test-invoke-stage/POST/shorten
    Metadata:
      aws:cdk:path: UrlShortenerSvcStack/ShortenerApi/Default/shorten/POST/ApiPermission.Test.UrlShortenerSvcStackShortenerApi3DEC1041.POST..shorten
  ShortenerApishortenPOST6FA1D6B0:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: POST
      ResourceId:
        Ref: ShortenerApishortenDE5AC227
      RestApiId:
        Ref: ShortenerApi3A8B5181
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - ShortenerFunction2C447D23
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: UrlShortenerSvcStack/ShortenerApi/Default/shorten/POST/Resource
  RedirectFunctionServiceRole098A3D15:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: UrlShortenerSvcStack/RedirectFunction/ServiceRole/Resource
  RedirectFunctionServiceRoleDefaultPolicy92D89BB5:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - dynamodb:BatchGetItem
              - dynamodb:ConditionCheckItem
              - dynamodb:DescribeTable
              - dynamodb:GetItem
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:Query
              - dynamodb:Scan
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - urlsTableD98564E7
                  - Arn
              - Ref: AWS::NoValue
        Version: "2012-10-17"
      PolicyName: RedirectFunctionServiceRoleDefaultPolicy92D89BB5
      Roles:
        - Ref: RedirectFunctionServiceRole098A3D15
    Metadata:
      aws:cdk:path: UrlShortenerSvcStack/RedirectFunction/ServiceRole/DefaultPolicy/Resource
  RedirectFunction7849A310:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: 75b8fcf3c5503c74e3314d6344ce8db363fac9620028f2deea1ced0526a0284a.zip
      Role:
        Fn::GetAtt:
          - RedirectFunctionServiceRole098A3D15
          - Arn
      Environment:
        Variables:
          TABLE_NAME:
            Ref: urlsTableD98564E7
      Handler: index.handler
      Runtime: nodejs16.x
    DependsOn:
      - RedirectFunctionServiceRoleDefaultPolicy92D89BB5
      - RedirectFunctionServiceRole098A3D15
    Metadata:
      aws:cdk:path: UrlShortenerSvcStack/RedirectFunction/Resource
      aws:asset:path: asset.75b8fcf3c5503c74e3314d6344ce8db363fac9620028f2deea1ced0526a0284a
      aws:asset:is-bundled: false
      aws:asset:property: Code
  RedirectApi23C11309:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: RedirectApi
    Metadata:
      aws:cdk:path: UrlShortenerSvcStack/RedirectApi/Resource
  RedirectApiDeploymentC7273DBE3c6c45e35589c6a20d28c640f8294974:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: RedirectApi23C11309
      Description: Automatically created by the RestApi construct
    DependsOn:
      - RedirectApishortUrlGETAD7F1CEF
      - RedirectApishortUrl06D0EC8A
    Metadata:
      aws:cdk:path: UrlShortenerSvcStack/RedirectApi/Deployment/Resource
  RedirectApiDeploymentStageprod027C6316:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: RedirectApi23C11309
      DeploymentId:
        Ref: RedirectApiDeploymentC7273DBE3c6c45e35589c6a20d28c640f8294974
      StageName: prod
    Metadata:
      aws:cdk:path: UrlShortenerSvcStack/RedirectApi/DeploymentStage.prod/Resource
  RedirectApishortUrl06D0EC8A:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - RedirectApi23C11309
          - RootResourceId
      PathPart: "{shortUrl}"
      RestApiId:
        Ref: RedirectApi23C11309
    Metadata:
      aws:cdk:path: UrlShortenerSvcStack/RedirectApi/Default/{shortUrl}/Resource
  RedirectApishortUrlGETApiPermissionUrlShortenerSvcStackRedirectApi769CC57DGETshortUrlDE298844:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - RedirectFunction7849A310
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: RedirectApi23C11309
            - /
            - Ref: RedirectApiDeploymentStageprod027C6316
            - /GET/*
    Metadata:
      aws:cdk:path: UrlShortenerSvcStack/RedirectApi/Default/{shortUrl}/GET/ApiPermission.UrlShortenerSvcStackRedirectApi769CC57D.GET..{shortUrl}
  RedirectApishortUrlGETApiPermissionTestUrlShortenerSvcStackRedirectApi769CC57DGETshortUrl5C81648F:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - RedirectFunction7849A310
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: RedirectApi23C11309
            - /test-invoke-stage/GET/*
    Metadata:
      aws:cdk:path: UrlShortenerSvcStack/RedirectApi/Default/{shortUrl}/GET/ApiPermission.Test.UrlShortenerSvcStackRedirectApi769CC57D.GET..{shortUrl}
  RedirectApishortUrlGETAD7F1CEF:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId:
        Ref: RedirectApishortUrl06D0EC8A
      RestApiId:
        Ref: RedirectApi23C11309
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - RedirectFunction7849A310
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: UrlShortenerSvcStack/RedirectApi/Default/{shortUrl}/GET/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/1WPwU7DMBBEv6V3Z6EgFXFsi7ghqsK92thLu01sR/GaKory79hOEeW0b8bjsfcBVitYLvASKm2aquUaxg9B3ahkHUYzOLTeJPMT65bU9ssVmFSLtjYI42t0Wti7fHTLO+oth5DUpBgtjHs/3y9z51vWQ8kVmlR4PGAIJAHWeSQNm6gbkg0GUtjxEYUuOKQiCrLuuHRd8YW61g+WnGT3RqVVjuXVGVLex15T6fwV16KZ30hO3mRrpmn6y5WP5SJ2x5x4j9JF+Xc98dY7w1L2dt4QnMPd9/IZnuB+cQ7MVR+dsCXYz/MHuDumE4EBAAA=
    Metadata:
      aws:cdk:path: UrlShortenerSvcStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Outputs:
  ShortenerApiEndpointBAA66F26:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: ShortenerApi3A8B5181
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: ShortenerApiDeploymentStageprodD11A25C3
          - /
  RedirectApiEndpointE556C272:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: RedirectApi23C11309
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: RedirectApiDeploymentStageprod027C6316
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

