name: urlShortener-to-AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: npm ci

    - name: Synthesize CloudFormation template
      run: npx cdk synth

    - name: Deploy CloudFormation stack
      uses: aws-actions/aws-cloudformation-deploy@v1
      with:
        stack-name: UrlShortenerSvcStack
        capabilities: CAPABILITY_NAMED_IAM
        template-file: ./cdk.out/UrlShortenerSvcStack.template.json

    - name: Deploy Lambda functions
      run: npx cdk deploy '*' --require-approval never
